// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContentDocumentDataSlicesSlice = ContentSlice;

/**
 * Content for Content documents
 */
interface ContentDocumentData {
  /**
   * Slice Zone field in *Content*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: content.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContentDocumentDataSlicesSlice>;
}

/**
 * Content document from Prismic
 *
 * - **API ID**: `content`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentDocumentData>,
    "content",
    Lang
  >;

type ExperiencesDocumentDataSlicesSlice = ExperiencesSlice;

/**
 * Content for Experiences documents
 */
interface ExperiencesDocumentData {
  /**
   * Slice Zone field in *Experiences*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExperiencesDocumentDataSlicesSlice>;
}

/**
 * Experiences document from Prismic
 *
 * - **API ID**: `experiences`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperiencesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExperiencesDocumentData>,
    "experiences",
    Lang
  >;

type FeedDocumentDataSlicesSlice = FeedPostSlice;

/**
 * Content for Feed documents
 */
interface FeedDocumentData {
  /**
   * Slice Zone field in *Feed*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: feed.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FeedDocumentDataSlicesSlice>;
}

/**
 * Feed document from Prismic
 *
 * - **API ID**: `feed`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeedDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FeedDocumentData>, "feed", Lang>;

type PageDocumentDataSlicesSlice =
  | PostSlice
  | ExperiencesSlice
  | FeedPostSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PostsDocumentDataSlicesSlice = PostSlice;

/**
 * Content for Posts documents
 */
interface PostsDocumentData {
  /**
   * Slice Zone field in *Posts*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: posts.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostsDocumentDataSlicesSlice>;
}

/**
 * Posts document from Prismic
 *
 * - **API ID**: `posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostsDocumentData>, "posts", Lang>;

type StoriesDocumentDataSlicesSlice = StoriesSlice;

/**
 * Content for Stories documents
 */
interface StoriesDocumentData {
  /**
   * Slice Zone field in *Stories*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: stories.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<StoriesDocumentDataSlicesSlice>;
}

/**
 * Stories document from Prismic
 *
 * - **API ID**: `stories`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StoriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<StoriesDocumentData>,
    "stories",
    Lang
  >;

export type AllDocumentTypes =
  | ContentDocument
  | ExperiencesDocument
  | FeedDocument
  | PageDocument
  | PostsDocument
  | StoriesDocument;

/**
 * Primary content in *Content → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Title field in *Content → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slug field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Type field in *Content → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Blog
   * - **API ID Path**: content.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Blog" | "External", "filled">;

  /**
   * Created In field in *Content → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.created_in
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  created_in: prismic.DateField;

  /**
   * locale field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.locale
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  locale: prismic.KeyTextField;
}

/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation = ContentSliceDefault;

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSlice = prismic.SharedSlice<
  "content",
  ContentSliceVariation
>;

/**
 * Primary content in *Experiences → Primary*
 */
export interface ExperiencesSliceDefaultPrimary {
  /**
   * Enterprise field in *Experiences → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.primary.enterprise
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  enterprise: prismic.TitleField;

  /**
   * Enterprise Logo field in *Experiences → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.primary.enterprise_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  enterprise_logo: prismic.ImageField<never>;

  /**
   * Locale field in *Experiences → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.primary.locale
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  locale: prismic.RichTextField;

  /**
   * Starts In field in *Experiences → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.primary.starts_in
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  starts_in: prismic.DateField;

  /**
   * Ends In field in *Experiences → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.primary.ends_in
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  ends_in: prismic.DateField;
}

/**
 * Primary content in *Experiences → Items*
 */
export interface ExperiencesSliceDefaultItem {
  /**
   * Role field in *Experiences → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.items[].role
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.RichTextField;

  /**
   * Starts In field in *Experiences → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.items[].starts_in
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  starts_in: prismic.DateField;

  /**
   * Ends In field in *Experiences → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.items[].ends_in
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  ends_in: prismic.DateField;

  /**
   * Skills field in *Experiences → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.items[].skills
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  skills: prismic.RichTextField;
}

/**
 * Default variation for Experiences Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperiencesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperiencesSliceDefaultPrimary>,
  Simplify<ExperiencesSliceDefaultItem>
>;

/**
 * Slice variation for *Experiences*
 */
type ExperiencesSliceVariation = ExperiencesSliceDefault;

/**
 * Experiences Shared Slice
 *
 * - **API ID**: `experiences`
 * - **Description**: Experiences
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperiencesSlice = prismic.SharedSlice<
  "experiences",
  ExperiencesSliceVariation
>;

/**
 * Primary content in *FeedPost → Primary*
 */
export interface FeedPostSliceDefaultPrimary {
  /**
   * Author field in *FeedPost → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feed_post.primary.author
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author: prismic.RichTextField;

  /**
   * Created At field in *FeedPost → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: feed_post.primary.createdat
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  createdat: prismic.TimestampField;

  /**
   * Pinned field in *FeedPost → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: feed_post.primary.pinned
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  pinned: prismic.BooleanField;

  /**
   * Text field in *FeedPost → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feed_post.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Locale field in *FeedPost → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feed_post.primary.locale
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  locale: prismic.RichTextField;

  /**
   * ProfilePhoto field in *FeedPost → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feed_post.primary.profilephoto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profilephoto: prismic.ImageField<never>;

  /**
   * Link field in *FeedPost → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feed_post.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *FeedPost → Items*
 */
export interface FeedPostSliceDefaultItem {
  /**
   * Image field in *FeedPost → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feed_post.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * primary variation for FeedPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeedPostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeedPostSliceDefaultPrimary>,
  Simplify<FeedPostSliceDefaultItem>
>;

/**
 * Slice variation for *FeedPost*
 */
type FeedPostSliceVariation = FeedPostSliceDefault;

/**
 * FeedPost Shared Slice
 *
 * - **API ID**: `feed_post`
 * - **Description**: FeedPost
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeedPostSlice = prismic.SharedSlice<
  "feed_post",
  FeedPostSliceVariation
>;

/**
 * Primary content in *Post → Primary*
 */
export interface PostSliceDefaultPrimary {
  /**
   * Slug field in *Post → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.primary.slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Title field in *Post → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: post.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Created In field in *Post → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: post.primary.created_in
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  created_in: prismic.DateField;

  /**
   * Read Time field in *Post → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: post.primary.read_time
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  read_time: prismic.NumberField;

  /**
   * Content field in *Post → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Post → Items*
 */
export interface PostSliceDefaultItem {
  /**
   * tagName field in *Post → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.items[].tagname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagname: prismic.KeyTextField;

  /**
   * Tag field in *Post → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: post.items[].tag
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tag: prismic.LinkField;
}

/**
 * Default variation for Post Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PostSliceDefaultPrimary>,
  Simplify<PostSliceDefaultItem>
>;

/**
 * Slice variation for *Post*
 */
type PostSliceVariation = PostSliceDefault;

/**
 * Post Shared Slice
 *
 * - **API ID**: `post`
 * - **Description**: Post
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostSlice = prismic.SharedSlice<"post", PostSliceVariation>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *Storie → Primary*
 */
export interface StoriesSliceDefaultPrimary {
  /**
   * Image field in *Storie → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stories.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Storie → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: stories.primary.video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video: prismic.EmbedField;

  /**
   * CreatedIn field in *Storie → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: stories.primary.createdin
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  createdin: prismic.TimestampField;
}

/**
 * Default variation for Storie Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StoriesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Storie*
 */
type StoriesSliceVariation = StoriesSliceDefault;

/**
 * Storie Shared Slice
 *
 * - **API ID**: `stories`
 * - **Description**: Stories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoriesSlice = prismic.SharedSlice<
  "stories",
  StoriesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContentDocument,
      ContentDocumentData,
      ContentDocumentDataSlicesSlice,
      ExperiencesDocument,
      ExperiencesDocumentData,
      ExperiencesDocumentDataSlicesSlice,
      FeedDocument,
      FeedDocumentData,
      FeedDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PostsDocument,
      PostsDocumentData,
      PostsDocumentDataSlicesSlice,
      StoriesDocument,
      StoriesDocumentData,
      StoriesDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentSlice,
      ContentSliceDefaultPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      ExperiencesSlice,
      ExperiencesSliceDefaultPrimary,
      ExperiencesSliceDefaultItem,
      ExperiencesSliceVariation,
      ExperiencesSliceDefault,
      FeedPostSlice,
      FeedPostSliceDefaultPrimary,
      FeedPostSliceDefaultItem,
      FeedPostSliceVariation,
      FeedPostSliceDefault,
      PostSlice,
      PostSliceDefaultPrimary,
      PostSliceDefaultItem,
      PostSliceVariation,
      PostSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      StoriesSlice,
      StoriesSliceDefaultPrimary,
      StoriesSliceVariation,
      StoriesSliceDefault,
    };
  }
}
