// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  feed_post: dynamic(() => import("./FeedPost")),
  rich_text: dynamic(() => import("./RichText")),
};
